PATCH /api/0.1/assets/ef68fbb73eca41ea9870335b79c65659?acc_token=4ef1c477b48f43718d7b089bca7aef07 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net

{
  "data": {
    "status": "pending"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "pending", 
    "assetType": "basic", 
    "classification": {
      "scheme": "CPV", 
      "description": "Земельні ділянки", 
      "id": "37452200-3"
    }, 
    "title": "Земля для космодрому", 
    "assetID": "UA-2017-08-14-000001", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2017-08-14T18:14:14.332878+03:00", 
    "owner": "broker", 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "address": {
      "postalCode": "79000", 
      "countryName": "Україна", 
      "streetAddress": "вул. Банкова 1", 
      "region": "м. Київ", 
      "locality": "м. Київ"
    }, 
    "date": "2017-08-14T18:14:14.332878+03:00", 
    "id": "ef68fbb73eca41ea9870335b79c65659", 
    "unit": {
      "code": "44617100-9", 
      "name": "item"
    }, 
    "quantity": 5
  }
}

